version: "3.8"

networks:
  monitoring_net:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-frontend
    restart: always

    # Expose seulement pour debug local
    # ports:
    #   - "3001:80"
    # Expose seulement pour debug localllll
    ports:
      - "3001:80"

    networks:
      - monitoring_net

    labels:
      - "traefik.enable=true"

      # Router principal -> stock-s.fr
      - "traefik.http.routers.front.rule=Host(`stock-s.fr`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=myresolver"

      # Router secondaire -> www.stock-s.fr
      - "traefik.http.routers.front-www.rule=Host(`www.stock-s.fr`)"
      - "traefik.http.routers.front-www.entrypoints=websecure"
      - "traefik.http.routers.front-www.tls.certresolver=myresolver"

      # Service backend interne
      - "traefik.http.services.front.loadbalancer.server.port=80"
