import type { RouteMeta } from "./types";

export const ROUTES: Record<string, RouteMeta> = {
  HOME: {
    path: '/',
    label: 'Home',
    page: 'Home',
    icon: 'home',
    restricted: false,
    layout: 'home',
    title: 'StockS',
  },
  LOGIN: {
    path: '/login',
    label: 'Login',
    page: 'Login',
    layout: 'auth',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Connexion',
  },
  DASHBOARD: {
    path: '/dashboard',
    label: 'Dashboard',
    page: 'Dashboard',
    icon: 'dashboard',
    restricted: true,
    roles: ['admin', 'manager'],
    layout: 'app',
    title: 'StockS - Dashboard',
  },
  USERS: {
    path: '/users',
    label: 'Users',
    page: 'Users',
    icon: 'users',
    restricted: true,
    roles: ['admin'],
    layout: 'app',
    title: 'StockS - Utilisateurs',
  },
  INVENTORY: {
    path: '/inventory',
    label: 'Inventory',
    page: 'Inventory',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Inventory',
  },
  PRODUCT_KPIS: {
    path: '/inventory/:id/kpis',
    label: 'Product KPIs',
    page: 'ProductKPIs',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    hiddenInMenu: true,
    title: 'StockS - Product KPIs',
  },
  INSIGHTS: {
    path: '/insights',
    label: 'Insights',
    page: 'Insights',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Insights',
  },
  PREDICTIONS: {
    path: '/predictions',
    label: 'Predictions',
    page: 'Predictions',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Prédictions IA',
  },
  SALES: {
    path: '/sales',
    label: 'Sales',
    page: 'Sales',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Sales',
  },
  PRICING_NEWS_ALERTS: {
    path: '/pricing-news-alerts',
    label: 'Pricing News & Alerts',
    page: 'PricingNewsAlerts',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Pricing News & Alerts',
  },
  SUPPLIERS: {
    path: '/suppliers',
    label: 'Suppliers',
    page: 'Suppliers',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Suppliers',
  },
  ORDERS: {
    path: '/orders',
    label: 'Orders',
    page: 'Orders',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Orders',
  },
  ORDER_KPIS: {
    path: '/orders/kpis',
    label: 'Order KPIs',
    page: 'OrderKPIs',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Statistiques commandes',
  },
  TEAM: {
    path: '/team',
    label: 'Team',
    page: 'Team',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Team',
  },
  ALERTS: {
    path: '/alerts',
    label: 'Alerts',
    page: 'Alerts',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Alertes & Prévisions IA',
  },
  LOYALTY: {
    path: '/loyalty',
    label: 'Loyalty',
    page: 'Loyalty',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Loyalty Program',
  },
  PROMOTIONS: {
    path: '/promotions',
    label: 'Promotions',
    page: 'Promotions',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Promotions & Remises',
  },
  SETTINGS: {
    path: '/settings',
    label: 'Settings',
    page: 'Settings',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Settings',
  },
  PROFILE: {
    path: '/profile',
    label: 'Profile',
    page: 'Profile',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Profil',
  },
  LOGOUT: {
    path: '/logout',
    label: 'Logout',
    page: 'Logout',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Logout',
  },
  NOTFOUND: {
    path: '*',
    label: 'NotFound',
    page: 'NotFound',
    layout: 'none',
    restricted: false,
    title: 'StockS - Page not found',
  },
  PLAYGROUND: {
    path: '/playground',
    label: 'Playground',
    page: 'Playground',
    layout: 'app',
    restricted: false,
    title: 'StockS - Playground',
  },
  displaySite: {
    path: '/DisplaySite',
    label: 'Display Site',
    page: 'DisplaySite',
    layout: 'none', // or 'none' if you want NO layout at all
    restricted: false,
  },

  TARIFS: {
    path: '/tarifs',
    label: 'Tarifs',
    page: 'Pricing',
    layout: 'none',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Tarifs',
  },
  APP_PRICING: {
    path: '/abonnement',
    label: 'Abonnement',
    page: 'Pricing',
    layout: 'app',
    restricted: true,
    title: 'StockS - Abonnement',
  },

  TERMS: {
    path: '/mentions-legales',
    label: 'CGU',
    page: 'Terms',
    layout: 'none',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Conditions Générales d\'Utilisation',
  },

  ABOUT: {
    path: '/a-propos',
    label: 'À propos',
    page: 'About',
    layout: 'none',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - À propos',
  },
  CONTACT: {
    path: '/contact',
    label: 'Contact',
    page: 'Contact',
    layout: 'none',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Contact',
  },
  PRIVACY: {
    path: '/confidentialite',
    label: 'Confidentialité',
    page: 'Privacy',
    layout: 'none',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Politique de confidentialité',
  },
  FEATURES: {
    path: '/fonctionnalites',
    label: 'Fonctionnalités',
    page: 'Features',
    layout: 'none',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Fonctionnalités',
  },

  DEMO: {
    path: '/demo',
    label: 'Demo',
    page: 'Demo',
    layout: 'none',
    restricted: false,
    title: 'StockS - Demo',
  },

};