import type { RouteMeta } from "./types";

export const ROUTES: Record<string, RouteMeta> = {
  HOME: {
    path: '/',
    label: 'Home',
    page: 'Home',
    icon: 'home',
    restricted: false,
    layout: 'home',
    title: 'StockS',
  },
  LOGIN: {
    path: '/login',
    label: 'Login',
    page: 'Login',
    layout: 'auth',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Connexion',
  },
  REGISTER: {
    path: '/register',
    label: 'Register',
    page: 'Register',
    layout: 'auth',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Inscription',
  },
  DASHBOARD: {
    path: '/dashboard',
    label: 'Dashboard',
    page: 'Dashboard',
    icon: 'dashboard',
    restricted: true,
    roles: ['admin', 'manager'],
    layout: 'app',
    title: 'StockS - Dashboard',
  },
  USERS: {
    path: '/users',
    label: 'Users',
    page: 'Users',
    icon: 'users',
    restricted: true,
    roles: ['admin'],
    layout: 'app',
    title: 'StockS - Utilisateurs',
  },
  INVENTORY: {
    path: '/inventory',
    label: 'Inventory',
    page: 'Inventory',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Inventory',
  },
  INSIGHTS: {
    path: '/insights',
    label: 'Insights',
    page: 'Insights',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Insights',
  },
  SALES: {
    path: '/sales',
    label: 'Sales',
    page: 'Sales',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Sales',
  },
  PRICING_NEWS_ALERTS: {
    path: '/pricing-news-alerts',
    label: 'Pricing News & Alerts',
    page: 'PricingNewsAlerts',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Pricing News & Alerts',
  },
  SUPPLIERS: {
    path: '/suppliers',
    label: 'Suppliers',
    page: 'Suppliers',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Suppliers',
  },
  ORDERS: {
    path: '/orders',
    label: 'Orders',
    page: 'Orders',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Orders',
  },
  AI_ASSISTANT: {
    path: '/ai-assistant',
    label: 'AI Assistant',
    page: 'AIAssistant',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - AI Assistant',
  },
  TEAM: {
    path: '/team',
    label: 'Team',
    page: 'Team',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Team',
  },
  SETTINGS: {
    path: '/settings',
    label: 'Settings',
    page: 'Settings',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Settings',
  },
  PROFILE: {
    path: '/profile',
    label: 'Profile',
    page: 'Profile',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Profil',
  },
  LOGOUT: {
    path: '/logout',
    label: 'Logout',
    page: 'Logout',
    layout: 'app',
    restricted: true,
    roles: ['admin', 'manager'],
    title: 'StockS - Logout',
  },
  NOTFOUND: {
    path: '*',
    label: 'NotFound',
    page: 'NotFound',
    layout: 'none',
    restricted: false,
    title: 'StockS - Page not found',
  },
  PLAYGROUND: {
    path: '/playground',
    label: 'Playground',
    page: 'Playground',
    layout: 'app',
    restricted: false,
    title: 'StockS - Playground',
  },
  displaySite: {
    path: '/DisplaySite',
    label: 'Display Site',
    page: 'DisplaySite',
    layout: 'none', // or 'none' if you want NO layout at all
    restricted: false,
  },

  TARIFS: {
    path: '/tarifs',
    label: 'Tarifs',
    page: 'Pricing',
    layout: 'none',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Tarifs',
  },
  APP_PRICING: {
    path: '/abonnement',
    label: 'Abonnement',
    page: 'Pricing',
    layout: 'app',
    restricted: true,
    title: 'StockS - Abonnement',
  },

  TERMS: {
    path: '/mentions-legales',
    label: 'CGU',
    page: 'Terms',
    layout: 'none',
    restricted: false,
    hiddenInMenu: true,
    title: 'StockS - Conditions Générales d\'Utilisation',
  },

};