import { lazy } from "react";

export const PAGES = {
  Home: lazy(() => import("@/ui/features/home/pages/HomePage")),
  DisplaySite: lazy(() => import("@/ui/features/home/pages/HomePage")),
  Pricing: lazy(() => import("@/ui/features/home/pages/PricingPage")),
  Terms: lazy(() => import("@/ui/features/home/pages/TermsPage")),
  Login: lazy(() => import("@/ui/features/auth/pages/AuthPage")),
  Dashboard: lazy(() => import("@/ui/features/dashboard/pages/DashboardPage")),
  Users: lazy(() => import("@/ui/features/team/pages/UsersPage")),
  NotFound: lazy(() => import("@/ui/pages/NotFoundPage")),
  Playground: lazy(() => import("@/ui/pages/PlaygroundPage")),
  Inventory: lazy(() => import("@/ui/features/inventory/pages/InventoryPage")),
  ProductKPIs: lazy(() => import("@/ui/features/inventory/pages/ProductKPIsPage/ProductKPIsPage")),
  Insights: lazy(() => import("@/ui/features/insights/pages/InsightsPage")),
  Sales: lazy(() => import("@/ui/features/sales/pages/SalesPage")),
  Clients: lazy(() => import("@/ui/features/clients/pages/ClientsPage")),
  PricingNewsAlerts: lazy(() => import("@/ui/features/pricing/pages/PricingNewsAlertsPage")),
  Suppliers: lazy(() => import("@/ui/features/suppliers/pages/SuppliersPage")),
  Orders: lazy(() => import("@/ui/features/orders/pages/OrdersPage")),
  Team: lazy(() => import("@/ui/features/team/pages/TeamPage")),
  Settings: lazy(() => import("@/ui/features/settings/pages/SettingsPage")),
  Profile: lazy(() => import("@/ui/features/profile/pages/ProfilePage")),
  Loyalty: lazy(() => import("@/ui/features/loyalty/pages/LoyaltyPage")),
  Alerts: lazy(() => import("@/ui/features/alerts/pages/AlertsPage")),
  Logout: lazy(() => import("@/ui/features/auth/pages/LogoutPage")),
  Demo: lazy(() => import("@/ui/features/home/pages/Demo")),
};
