name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

env:
  ANSIBLE_HOST_KEY_CHECKING: False
  ANSIBLE_FORCE_COLOR: True

jobs:
  # ========== JOB 1 : SETUP ==========
  setup:
    runs-on: ubuntu-latest
    container:
      image: cytopia/ansible:2.10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: |
          apk update
          apk add openssh

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Upload SSH known_hosts
        uses: actions/upload-artifact@v4
        with:
          name: known-hosts
          path: ~/.ssh/known_hosts

    # ========== JOB 2 : DEPLOYMENT ==mm========ss
  deploy:
    runs-on: ubuntu-latest
    container:
      image: cytopia/ansible:2.10
    needs: [setup]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Download known_hosts
        uses: actions/download-artifact@v4
        with:
          name: known-hosts
          path: ~/.ssh

      - name: Deploy with Ansible
        run: |
          ansible-playbook \
            -i ansible/inventory.yml \
            ansible/playbooks/site.yml \
            --private-key ~/.ssh/id_rsa \
            --extra-vars "github_token=${{ secrets.GH_TOKEN }}"

  # ========== JOB 3 : MONITORING ==========
  monitoring:
    runs-on: ubuntu-latest
    container:
      image: cytopia/ansible:2.10
    needs: [setup, deploy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Download known_hosts
        uses: actions/download-artifact@v4
        with:
          name: known-hosts
          path: ~/.ssh

      - name: Deploy monitoring
        run: |
          ansible-playbook \
            -i ansible/inventory.yml \
            ansible/playbooks/monitor.yml \
            --private-key ~/.ssh/id_rsa \
            --extra-vars "github_token=${{ secrets.GH_TOKEN }}"
